//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaOTEK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesDireccionesRelacion
    {
        public int ID { get; set; }
        public Nullable<int> ID_Clientes { get; set; }
        public Nullable<int> ID_Direcciones { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Direccione Direccione { get; set; }
    }
}
